development:
  adapter: postgresql
  database: lvtc_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: lvtc_production
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: lvtc_test
  pool: 5
  timeout: 5000
